default_platform(:android)
platform :android do
  desc "Submit a new internal build to Play Store"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: '../android/app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end